# Generated by Django 4.2.6 on 2023-11-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Subscribe',
        ),
    ]
