# Generated by Django 4.2.6 on 2023-11-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscribe', '0002_rename_user_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='notif',
            field=models.CharField(choices=[('W', 'WEEKLY'), ('M', 'MONTHLY')], default='W', max_length=2),
            preserve_default=False,
        ),
    ]
