# Generated by Django 4.2.6 on 2023-11-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscribe', '0003_subscribe_notif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='notif',
            field=models.CharField(choices=[('W', 'WEEKLY'), ('M', 'MONTHLY')], default='W', max_length=2),
        ),
    ]
