# Generated by Django 4.2.6 on 2023-11-02 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 2, 12, 11, 52, 405727, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='Salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
