# Generated by Django 4.2.6 on 2023-11-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_jobpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='Expiry',
            field=models.DateField(null=True),
        ),
    ]
