# Generated by Django 4.2.6 on 2023-11-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_location_jobpost_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='Descr',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='Expiry',
            new_name='expiry',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='Salary',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='Title',
            new_name='title',
        ),
    ]
